variables:
  GIT_SUBMODULE_STRATEGY: none

stages:
  - check
  - trigger_pipeline

build_proto:
  stage: check
  image: docker-registry.thunics.org:5000/bstack2proto3:v1.2.2
  script:
    - export COMPILE_PATH=.Rebuild
    - mkdir ${COMPILE_PATH}
    - cd ${COMPILE_PATH}
    - echo "step1:clone MessageProto..."
    - echo "MessageProto branch:${CI_COMMIT_REF_NAME}"
    - git clone -b ${CI_COMMIT_REF_NAME} http://git.thunics.org/dp/MessageProto.git
    - echo "step2:clone wsn-data..."
    - git clone -b master http://git.thunics.org/embedded/wsn-data.git
    - echo "step3:check MessageProto"
    - /home/work/bstack2proto3/BStack2Proto3 > result.txt
    - RESULT=`awk '$1 ~ /congratulation/ {print "yes"}' result.txt`
    - if [ "${RESULT}" == "yes" ]; then echo "MessageProto check success"; else echo "MessageProto check failed"; cat result.txt; exit 1; fi
    - cd MessageProto
    - enable_commit=`git status|awk '$0 ~ /nothing to commit, working tree clean/ {print "no"}'`
    - if [ "${enable_commit}" != "no" ]; then git add .; git commit -m "update:update proto --user=robot"; git push; fi
    - cd ../..
    - rm -rf ${COMPILE_PATH}
  only:
    - master
    - develop
    - tags
  tags:
    - gitlab-runner-db-test01

trigger_robot:
  stage: trigger_pipeline
  before_script:
    - apk add --no-cache curl
  script:
    - echo "trigger MQTT2Pulsar update MessageProto..."
    - curl -X POST -F token=b48ccbf57b8f58369ba3b3e3657181 -F ref=master http://git.thunics.org/api/v4/projects/742/trigger/pipeline
    - curl -X POST -F token=b48ccbf57b8f58369ba3b3e3657181 -F ref=develop http://git.thunics.org/api/v4/projects/742/trigger/pipeline
  only:
    - master
    - tags
  when: manual
  tags:
    - gitlab-runner-db-test01