
before_script:
  - sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
  - apk add --no-cache tzdata git gettext

stages:
  - build

translate_protobuf:
  stage: build
  image: docker:latest
  script:
    - mkdir make
    - cd make
    - git clone http://songxiaopeng:1016593219Sxp@git.thunics.org/dp/BStack2Proto3.git
    - cd BStack2Proto3/make
    - tar xzvf libs.tar.gz
    - git clone http://songxiaopeng:1016593219Sxp@git.thunics.org/embedded/wsn-data.git
    - git clone http://songxiaopeng:1016593219Sxp@git.thunics.org/dp/MessageProto.git
    - ./BStack2Proto3.sh || if [ $? -eq 0 ]; then echo "translate success"; else exit 255; fi
  when: manual
  only: 
    - master
  tags: 
    - gitlab-runner-sb4