variables:
  GIT_SUBMODULE_STRATEGY: none

stages:
  - check
  - trigger_pipeline

build_proto:
  stage: check
  image: docker-registry.thunics.org:5000/bstack2proto3:v1.2.2
  script:
    - ./rebuild.sh || if [ $? -eq 1 ]; then echo "rebuild failed"; exit 1; else echo "rebuild success"; fi
    - cd .Rebuild/MessageProto
    - enable_commit=`git status|awk '$0 ~ /nothing to commit, working tree clean/ {print "no"}'`
    - if [ "${enable_commit}" == "no" ]; then rm -rf .Rebuild; exit 0; fi
    - git add .
    - git commit -m "update:update proto --user=robot"
    - git push
    - rm -rf .Rebuild
  only:
    - master
    - develop
    - tags
  tags:
    - gitlab-runner-db-test01

trigger_robot:
  stage: trigger_pipeline
  script:
    - echo "trigger MQTT2Pulsar update MessageProto..."
    - curl -X POST -F token=b48ccbf57b8f58369ba3b3e3657181 -F ref=master http://git.thunics.org/api/v4/projects/742/trigger/pipeline
    - curl -X POST -F token=b48ccbf57b8f58369ba3b3e3657181 -F ref=develop http://git.thunics.org/api/v4/projects/742/trigger/pipeline
  only:
    - master
    - tags
  tags:
    - gitlab-runner-db-test01