variables:
  GIT_SUBMODULE_STRATEGY: none

stages:
  - check
  - manual_check

build_proto_variable:
  stage: check
  image: docker-registry.thunics.org:5000/bstack2proto3:v1.2.2
  script:
    - if [ "${RUN_BUILD}" != "yes" ]; then exit 0; fi
    - ./rebuild.sh || if [ $? -eq 1 ]; then echo "rebuild failed"; exit 1; else echo "rebuild success"; fi
    - pwd
    - rm -rf .Rebuild
  only:
    - master
    - develop
    - tags
  tags:
    - gitlab-runner-db-test01

build_proto_manual:
  stage: check
  image: docker-registry.thunics.org:5000/bstack2proto3:v1.2.2
  script:
    - ./rebuild.sh || if [ $? -eq 1 ]; then echo "rebuild failed"; exit 1; else echo "rebuild success"; fi
    - cd .Rebuild/MessageProto
    - ls -l
    - status_result=`git status|awk '$0 ~ /nothing to commit, working tree clean/ {print "yes"}'`
    - echo ${status_result}
    - rm -rf .Rebuild
  only:
    - master
    - develop
    - tags
  when: manual
  tags:
    - gitlab-runner-db-test01

